base_url = "https://getzola.github.io/hyde/"
compile_sass = true
title = "Hyde theme"
description = "A clean blogging theme"
generate_feed = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "https://google.com", name = "About"},
]
